[package]
name = "viper"
version = "0.0.1"
authors = ["Steve Akinyemi <appcypher@outlook.com>"]
edition = "2018"

[dependencies]
viper-lexer = { path = "compiler/lexer" }
viper-parser = { path = "compiler/parser" }
viper-codegen = { path = "compiler/codegen" }
